### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by werff** [KAMKEEL/CustomNPC-DBC-Addon#7]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/10/24 12:33
Description: Initializing game

java.lang.NoClassDefFoundError: kamkeel/npcdbc/client/render/AuraRenderer
	at net.minecraft.client.Minecraft.handler$zdi000$npcdbc$onRefresh(Minecraft.java:2966)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:628)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:238)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: kamkeel.npcdbc.client.render.AuraRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: JinRyuu/DragonBC/common/Npcs/RenderDBC
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 14 more
Caused by: java.lang.ClassNotFoundException: JinRyuu.DragonBC.common.Npcs.RenderDBC
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.handler$zdi000$npcdbc$onRefresh(Minecraft.java:2966)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:628)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:238)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 375487336 bytes (358 MB) / 603979776 bytes (576 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	U	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	U	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	U	unimixins{0.1.17} [UniMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	unimixins-compat{0.1.17} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	mixinextras{0.1.17} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.17.jar) 
	U	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	U	trop{4.0} [The Rings of Power] ([1.7.10]+The+Rings+of+Power+v4.0.jar) 
	U	forgecreeperheal{1.1.1} [Forge Creeper Heal 1.1.1] ([1.7.10]ForgeCreeperHeal-1.1.1.jar) 
	U	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	U	alluwant{2.1} [All U Want] (All-U-Want 2.1.jar) 
	U	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	U	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	U	customnpcs{1.9.3} [CustomNPC+] (CustomNPC-Plus-1.9.3.jar) 
	U	lootablebodies{1.3.7} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.7.jar) 
	U	difficultlife{1.3.1710.0} [Difficult Life] (difficultlife-1.3.1710.0.jar) 
	U	jinryuudragonblockc{1.4.85} [Dragon Block C] (DragonBlockC-v1.4.85.jar) 
	U	drealm{3.0} [Dwarven Realm] (Dwarven+Realm+v3.0.jar) 
	U	etfuturum{2.6.0} [Et Futurum Requiem] (Et_Futurum_Requiem-2.6.0.jar) 
	U	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	U	IronFist{1.3.1} [Iron Fist] (ironfist-1.3.1.jar) 
	U	jinryuubetterrenderaddon{1.6.52} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.52.jar) 
	U	journeymap{5.1.4p6} [JourneyMap] (journeymap-1.7.10-5.1.4p6-unlimited.jar) 
	U	jinryuujrmcore{1.3.51} [JinRyuu's JRMCore] (JRMCore-v1.3.51.jar) 
	U	legendarium{3} [Legendary Item 3] (Legendary_Item_3.jar) 
	U	lotr{Update v36.14 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRMod+v36.14.jar) 
	U	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	U	minefantasy2{2.8.14.6} [MineFantasyII] (MineFantasyII-2.8.14.6.jar) 
	U	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	U	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.1.jar) 
	U	moreplayermodels{3.0} [MorePlayerModels+] (MorePlayerModels-Plus-3.0.jar) 
	U	neirecipehandlers{1.1.0-BETA} [NEI Recipe Handlers] (neiRecipeHandlers-1.1.0-BETA.jar) 
	U	nodami{1.0} [No Damage Immunity (NoDamI)] (nodami-1.7.10-1.0.jar) 
	U	npcdbc{1.0} [CustomNPC-Plus-DBC-Addon] (npcdbc-1.0.jar) 
	U	plug{5.1} [The Plugin Mod] (PluginMod-5.1.jar) 
	U	shouldersurfing{1.10.1} [Shoulder Surfing] (ShoulderSurfing-1.7.10-1.10.1.jar) 
	U	SparksHammers{1.7.10-1.6} [Spark's Hammers] (SparksHammers-1.7.10-1.6.1.jar) 
	U	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	U	tinkersdefense{1.2} [Tinkers' Defense] (Tinkers-Defense-1.2.1.jar) 
	U	wolfarmor{1.3.0} [Wolf Armor and Storage] (wolfarmor-1.3.0.1.jar) 
	U	fyresmodjam{0.0.3f} [The You Will Die Mod] (You_Will_Die_Mod-0.0.3f.jar) 
	U	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.29' Renderer: 'NVIDIA GeForce GTX 1050/PCIe/SSE2'
	Mixins in Stacktrace: 
		net.minecraft.client.Minecraft:
			mixins.npcdbc.json:client.MixinMinecraft from mod npcdbc
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.29, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by captinwill** [comment]
this is an error the dev must fix, as EVERYBODY is crashing. shit mod

**Comment by FiveNights21611** [comment]
There is a fix for this:
Just use UniMixins, it doesn't seem to work with any other Mixin mod from experience
